[package]
name = "image_cipher"
version = "0.2.0"
authors = ["Luis Prado <lpradopostigo@gmail.com>"]
edition = "2018"
[lib]
crate-type = ["lib"]
[dependencies]
image = "0.23.14"
[profile.release]
lto = true
