[package]
name = "image_cipher"
version = "0.2.0"
authors = ["Luis Prado <lpradopostigo@gmail.com>"]
edition = "2021"
[lib]
crate-type = ["rlib"]

[dependencies]
# wasm-bindgen = "0.2"
image = "0.23.14"
